import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "@/app/globals.css";
import GeneralNavbar from "@/components/layout/general/navbar/GeneralNavbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={`flex flex-col min-h-screen`}>
            <GeneralNavbar/>
            <main className={`flex-grow`}>
                {children}
            </main>
            <footer className={`w-full flex flex-row justify-between bg-primary`}>
                <div>
                    Contact us
                </div>
            </footer>
        </div>
    );
}
